In [27]:
import numpy as np

In [28]:
mylist = [1,2,3]

In [29]:
type(mylist)

list

In [30]:
myArray = np.array(mylist)

In [31]:
myArray

array([1, 2, 3])

In [32]:
type(myArray)

numpy.ndarray

In [33]:
# two dimentional array

In [34]:
np.arange(3)

array([0, 1, 2])

In [35]:
np.arange(3.0)

array([0., 1., 2.])

In [36]:
np.arange(2.0)

array([0., 1.])

In [37]:
np.arange(2,6)

array([2, 3, 4, 5])

In [38]:
np.arange(2,8,2)

array([2, 4, 6])

In [39]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [40]:
# creating  2 dimentional array

In [41]:
np.zeros(4)

array([0., 0., 0., 0.])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
type(0)

int

In [45]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.random.seed(101)

In [48]:
arr = np.random.randint(2,size=5)

In [49]:
arr


array([1, 1, 1, 0, 1])

In [51]:
np.random.randint(1, size=3)

array([0, 0, 0])

In [56]:
np.random.randint(3,size=(2,3))

array([[1, 2, 0],
       [0, 1, 2]])

In [62]:
np.random.randint(6, size=(3,3))

array([[5, 5, 2],
       [2, 2, 4],
       [3, 3, 2]])

In [69]:
np.random.randint(1,[10,3,5])

array([6, 1, 4])

In [71]:
np.random.randint([2,2,2], 10)

array([5, 7, 8])

In [84]:
np.random.randint([2,3,5,4], [[12],[19]])

array([[10,  9,  9,  6],
       [18,  7, 14,  5]])

In [99]:
np.random.randint([1,2,3],[[10],[24],[24]])

array([[ 8,  8,  9],
       [15,  9, 10],
       [10,  6, 19]])

In [108]:
arr1=np.random.randint(0,100,10)


In [109]:
arr1

array([51, 49, 74, 82, 37, 53, 93, 73,  5, 37])

In [110]:
arr1.max()

93

In [111]:
arr1.argmax()

6

In [112]:
arr1.min()

5

In [113]:
arr1.argmin()

8

In [114]:
arr1.mean()

55.4

In [115]:
arr.shape

(5,)

In [116]:
arr1.shape

(10,)

In [119]:
arr1.reshape((2,5))

array([[51, 49, 74, 82, 37],
       [53, 93, 73,  5, 37]])

In [120]:
arr1.reshape((5,2))

array([[51, 49],
       [74, 82],
       [37, 53],
       [93, 73],
       [ 5, 37]])

In [121]:
mat = np.arange(0,100).reshape(10,10)

In [122]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [123]:
mat.shape

(10, 10)

In [124]:
row = 0
col = 1

In [125]:
mat[row,col]

1

In [126]:
row = 5
col = 4

In [127]:
mat[row,col]

54

In [128]:
mat[:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [130]:
mat[:,1].shape

(10,)

In [131]:
mat[:,1].reshape(1,10)

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [134]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [135]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [136]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
mat[0:3, 4:9]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28]])

In [138]:
mat[0:3, 4:9] = 0

In [140]:
newmat = mat.copy()

In [141]:
newmat

array([[ 0,  1,  2,  3,  0,  0,  0,  0,  0,  9],
       [10, 11, 12, 13,  0,  0,  0,  0,  0, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [142]:
newmat[0:6,:] = 999

In [143]:
newmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])