In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
myArray = np.array(mylist)

In [6]:
myArray

array([1, 2, 3])

In [7]:
type(myArray)

numpy.ndarray

In [8]:
# two dimentional array

In [9]:
np.arange(3)

array([0, 1, 2])

In [10]:
np.arange(3.0)

array([0., 1., 2.])

In [11]:
np.arange(2.0)

array([0., 1.])

In [12]:
np.arange(2,6)

array([2, 3, 4, 5])

In [13]:
np.arange(2,8,2)

array([2, 4, 6])

In [14]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
# creating  2 dimentional array

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
type(0)

int

In [20]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.random.seed(101)

In [23]:
arr = np.random.randint(2,size=5)

In [24]:
arr


array([1, 1, 1, 0, 1])

In [25]:
np.random.randint(1, size=3)

array([0, 0, 0])

In [26]:
np.random.randint(3,size=(2,3))

array([[1, 1, 1],
       [0, 0, 0]])

In [27]:
np.random.randint(6, size=(3,3))

array([[5, 4, 4],
       [0, 5, 4],
       [5, 0, 1]])

In [28]:
np.random.randint(1,[10,3,5])

array([4, 2, 3])

In [29]:
np.random.randint([2,2,2], 10)

array([2, 5, 7])

In [30]:
np.random.randint([2,3,5,4], [[12],[19]])

array([[ 5,  5,  9,  4],
       [12, 15, 16, 11]])

In [31]:
np.random.randint([1,2,3],[[10],[24],[24]])

array([[ 1,  3,  4],
       [16, 10,  7],
       [20,  5, 10]])

In [32]:
arr1=np.random.randint(0,100,10)


In [33]:
arr1

array([10, 52, 56, 38, 73, 52, 18, 71, 15, 44])

In [34]:
arr1.max()

73

In [35]:
arr1.argmax()

4

In [36]:
arr1.min()

10

In [37]:
arr1.argmin()

0

In [38]:
arr1.mean()

42.9

In [39]:
arr.shape

(5,)

In [40]:
arr1.shape

(10,)

In [41]:
arr1.reshape((2,5))

array([[10, 52, 56, 38, 73],
       [52, 18, 71, 15, 44]])

In [42]:
arr1.reshape((5,2))

array([[10, 52],
       [56, 38],
       [73, 52],
       [18, 71],
       [15, 44]])

In [43]:
mat = np.arange(0,100).reshape(10,10)

In [44]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat.shape

(10, 10)

In [46]:
row = 0
col = 1

In [47]:
mat[row,col]

1

In [48]:
row = 5
col = 4

In [49]:
mat[row,col]

54

In [50]:
mat[:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
mat[:,1].shape

(10,)

In [52]:
mat[:,1].reshape(1,10)

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [53]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [54]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [55]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
mat[0:3, 4:9]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28]])

In [57]:
mat[0:3, 4:9] = 0

In [58]:
newmat = mat.copy()

In [59]:
newmat

array([[ 0,  1,  2,  3,  0,  0,  0,  0,  0,  9],
       [10, 11, 12, 13,  0,  0,  0,  0,  0, 19],
       [20, 21, 22, 23,  0,  0,  0,  0,  0, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [60]:
newmat[0:6,:] = 999

In [61]:
newmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])